//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quản_lý_nhân_sự_doanh_nghiệp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataScope
    {
        public int ScopeId { get; set; }
        public int RoleId { get; set; }
        public int BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Role Role { get; set; }
    }
}
