//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quản_lý_nhân_sự_doanh_nghiệp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPlacement
    {
        public int PlacementId { get; set; }
        public int EmployeeId { get; set; }
        public int DepartmentId { get; set; }
        public int PositionId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
    }
}
