//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quản_lý_nhân_sự_doanh_nghiệp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int MaVaiTro { get; set; }
        public string MaChucNang { get; set; }
        public bool CoXem { get; set; }
        public bool CoThem { get; set; }
        public bool CoSua { get; set; }
        public bool CoXoa { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
