//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quản_lý_nhân_sự_doanh_nghiệp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeClockRaw
    {
        public long LogId { get; set; }
        public int MachineId { get; set; }
        public string EmpCode { get; set; }
        public System.DateTime PunchTime { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
